LoveJam = LoveJam or {}
LvLK3D = LvLK3D or {}
local levelData = {
	name = "level_tuto",
	nextLevel = "level1",
	isNoVis = false,
	gW = 0,
	gH = 0,
	gOX = 0,
	gOY = 0,
	deco = {
		[1] = {
			pos = Vector(4, 6, 8),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[2] = {
			pos = Vector(-4, 6, 8),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[3] = {
			pos = Vector(0, 0, 8),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[4] = {
			pos = Vector(0, 9, 8),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 6),
			mat = "metal_wall_stack2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[5] = {
			pos = Vector(8, 6, 0),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[6] = {
			pos = Vector(0, 0, -6),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 8),
			mat = "concrete1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 8,
		},
		[7] = {
			pos = Vector(-8, 6, -6),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 8),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 6,
		},
		[8] = {
			pos = Vector(12, 0, -10),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 4),
			mat = "concrete1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 4,
		},
		[9] = {
			pos = Vector(14, 6, -4),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 6,
		},
		[10] = {
			pos = Vector(8, 6, -4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[11] = {
			pos = Vector(0, 6, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 6,
		},
		[12] = {
			pos = Vector(8, 6, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[13] = {
			pos = Vector(20, 6, -9),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 3),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 3,
			uvScaleY = 6,
		},
		[14] = {
			pos = Vector(14, 0, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 1, 2),
			mat = "concrete1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 2,
		},
		[15] = {
			pos = Vector(6, 0, -24),
			ang =  Angle(0, 0, 0),
			scl = Vector(12, 1, 6),
			mat = "concrete1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 6,
		},
		[16] = {
			pos = Vector(12, 6, -32),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 6,
		},
		[17] = {
			pos = Vector(-8, 6, -24),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 6,
		},
		[18] = {
			pos = Vector(-4, 6, -36),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[19] = {
			pos = Vector(4, 6, -36),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[20] = {
			pos = Vector(0, 9, -36),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 6),
			mat = "metal_wall_stack2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[21] = {
			pos = Vector(0, 0, -36),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[22] = {
			pos = Vector(0, 3, 11),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 0.5),
			mat = "metal3",
			mdl = "cube",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[23] = {
			pos = Vector(0, 3, -40),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 0.5),
			mat = "metal3",
			mdl = "cube",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[24] = {
			pos = Vector(14, 12, -14),
			ang =  Angle(180, 0, 0),
			scl = Vector(24, 2, 16),
			mat = "metal4",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 24,
			uvScaleY = 16,
		},
		[25] = {
			pos = Vector(20, 3, -19),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 7),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 7,
			uvScaleY = 3,
		},
		[26] = {
			pos = Vector(20, 6, -28),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[27] = {
			pos = Vector(27, 9, -10),
			ang =  Angle(0, 0, 0),
			scl = Vector(5, 3, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 5,
			uvScaleY = 3,
		},
		[28] = {
			pos = Vector(27, 9, -28),
			ang =  Angle(0, 0, 0),
			scl = Vector(5, 3, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 5,
			uvScaleY = 3,
		},
		[29] = {
			pos = Vector(34, 9, -19),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 7),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 7,
			uvScaleY = 3,
		},
		[30] = {
			pos = Vector(20, 7.5, -13),
			ang =  Angle(0, 337.5, 0),
			scl = Vector(2, 2, 2),
			mat = "barrel_sheet",
			mdl = "barrel",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[31] = {
			pos = Vector(20, 7, -20),
			ang =  Angle(0, 337.5, 0),
			scl = Vector(1, 1, 1),
			mat = "metal2",
			mdl = "push_box",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
	},
	lights = {
		[1] = {
			pos = Vector(0, 5, 9),
			int = 4,
			col = Vector(255, 16, 16),
		},
		[2] = {
			pos = Vector(0, 10, -10),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[3] = {
			pos = Vector(-2, 10, -24),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[4] = {
			pos = Vector(25, 10, -15),
			int = 8,
			col = Vector(128, 196, 255),
		},
		[5] = {
			pos = Vector(0, 5, -38),
			int = 4,
			col = Vector(255, 16, 16),
		},
	},
	tiles = {
		[0] = {[0] = 1, [1] = 1, [2] = 4, [3] = 2, [-2] = 1, [-5] = 1, [-4] = 2, [-10] = 1, [-9] = 5, [-8] = 1, [-3] = 1, [-7] = 1, [-1] = 1, [-6] = 1, },
		[1] = {[0] = 1, [1] = 2, [2] = 2, [3] = 2, [-2] = 1, [-5] = 1, [-4] = 2, [-10] = 2, [-9] = 2, [-8] = 2, [-3] = 1, [-7] = 1, [-1] = 1, [-6] = 1, },
		[2] = {[0] = 2, [1] = 2, [-1] = 2, [-2] = 1, [-5] = 1, [-3] = 1, [-7] = 1, [-4] = 2, [-8] = 2, [-6] = 1, },
		[3] = {[-1] = 2, [-2] = 1, [-5] = 1, [-3] = 1, [-7] = 1, [-4] = 1, [-8] = 2, [-6] = 1, },
		[4] = {[-1] = 2, [-2] = 1, [-5] = 1, [-3] = 1, [-7] = 1, [-4] = 1, [-8] = 2, [-6] = 1, },
		[5] = {[-8] = 2, [-2] = 2, [-5] = 2, [-3] = 2, [-7] = 2, [-4] = 2, [-1] = 2, [-6] = 2, },
		[-2] = {[0] = 2, [1] = 2, [-1] = 2, [-2] = 2, [-5] = 2, [-3] = 2, [-7] = 2, [-4] = 2, [-8] = 2, [-6] = 2, },
		[-1] = {[0] = 1, [1] = 2, [2] = 2, [3] = 2, [-2] = 1, [-5] = 1, [-4] = 2, [-10] = 2, [-9] = 2, [-8] = 2, [-3] = 1, [-7] = 1, [-1] = 1, [-6] = 1, },
	},
}

LoveJam.DeclareLevel("level_tuto", levelData)