LoveJam = LoveJam or {}
LvLK3D = LvLK3D or {}
local levelData = {
	name = "levelfinal",
	nextLevel = "none",
	isNoVis = false,
	trackOverride = "sounds/music/nuclear.wav",
	gW = 0,
	gH = 0,
	gOX = 0,
	gOY = 0,
	deco = {
		[1] = {
			pos = Vector(10, 1, -15),
			ang =  Angle(0, 337.5, 0),
			scl = Vector(1, 1, 1),
			mat = "metal2",
			mdl = "push_box",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[2] = {
			pos = Vector(-4, 4, 2),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 4, 8),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 4,
		},
		[3] = {
			pos = Vector(0, -1, -29),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 9),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 9,
		},
		[4] = {
			pos = Vector(0, -1, -13),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 1, 7),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 7,
		},
		[5] = {
			pos = Vector(9, 16, -49),
			ang =  Angle(315, 45, 0),
			scl = Vector(3, 3, 3),
			mat = "toxic",
			mdl = "cube",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 3,
			uvScaleY = 3,
		},
		[6] = {
			pos = Vector(12, 3, -5),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 4, 1),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 4,
		},
		[7] = {
			pos = Vector(0, -1, -44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 2),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 2,
		},
		[8] = {
			pos = Vector(0, -17, -39),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 1, 19),
			mat = "toxic",
			mdl = "cube",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 8,
			uvScaleY = 8,
		},
		[9] = {
			pos = Vector(-12, 4, -5),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 4, 1),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 4,
		},
		[10] = {
			pos = Vector(-4, -1, -40),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[11] = {
			pos = Vector(0, 0, -59),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 18, 1),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 18,
		},
		[12] = {
			pos = Vector(-12, 0, -13),
			ang =  Angle(0, 0, 292.5),
			scl = Vector(1, 1, 1),
			mat = "robot_legl",
			mdl = "robot_legl",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[13] = {
			pos = Vector(-19, 4, -13),
			ang =  Angle(0, 0, 0),
			scl = Vector(1, 9, 7),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 7,
			uvScaleY = 9,
		},
		[14] = {
			pos = Vector(-12, 0.5, -13),
			ang =  Angle(0, 22.5, 315),
			scl = Vector(1, 1, 1),
			mat = "robot_hull",
			mdl = "robot_hull",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[15] = {
			pos = Vector(19, 4, -13),
			ang =  Angle(0, 0, 0),
			scl = Vector(1, 9, 7),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 7,
			uvScaleY = 9,
		},
		[16] = {
			pos = Vector(-13, -1, -13),
			ang =  Angle(270, 67.5, 45),
			scl = Vector(1, 1, 1),
			mat = "robot_legr",
			mdl = "robot_legr",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[17] = {
			pos = Vector(9, -1, -49),
			ang =  Angle(0, 0, 0),
			scl = Vector(1, 16, 1),
			mat = "toxic",
			mdl = "cube",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 1,
			uvScaleY = 16,
		},
		[18] = {
			pos = Vector(0, 7, 2),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 8),
			mat = "metal_wall_stack2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 1,
		},
		[19] = {
			pos = Vector(4, 4, 2),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 4, 8),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 4,
		},
		[20] = {
			pos = Vector(0, -9, -19),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 7, 1),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 7,
		},
		[21] = {
			pos = Vector(4, -1, -40),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[22] = {
			pos = Vector(0, 15, -41),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 1, 18),
			mat = "metal_floor1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 18,
		},
		[23] = {
			pos = Vector(19, -2, -39),
			ang =  Angle(0, 0, 0),
			scl = Vector(1, 16, 19),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 19,
			uvScaleY = 16,
		},
		[24] = {
			pos = Vector(0, 11, -14),
			ang =  Angle(337.5, 0, 0),
			scl = Vector(18, 1, 10),
			mat = "metal_floor1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 10,
		},
		[25] = {
			pos = Vector(12, 2, -13),
			ang =  Angle(0, 0, 0),
			scl = Vector(3, 3, 3),
			mat = "barrel_sheet",
			mdl = "barrel",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[26] = {
			pos = Vector(-19, -2, -39),
			ang =  Angle(0, 0, 0),
			scl = Vector(1, 16, 19),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 19,
			uvScaleY = 16,
		},
		[27] = {
			pos = Vector(0, 3, 7),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 1),
			mat = "metal3",
			mdl = "cube",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[28] = {
			pos = Vector(0, -1, 2),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 8),
			mat = "grate1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[29] = {
			pos = Vector(0, 7, -48),
			ang =  Angle(270, 0, 0),
			scl = Vector(4, 1, 4),
			mat = "fsign1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[30] = {
			pos = Vector(3, 12, -48),
			ang =  Angle(270, 270, 0),
			scl = Vector(2, 1, 2),
			mat = "chain",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 1,
		},
		[31] = {
			pos = Vector(-3, 12, -48),
			ang =  Angle(270, 270, 0),
			scl = Vector(2, 1, 2),
			mat = "chain",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 1,
		},
		[32] = {
			pos = Vector(3, 2, -19),
			ang =  Angle(0, 0, 0),
			scl = Vector(0.2, 2, 0.2),
			mat = "metal1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 0.2,
			uvScaleY = 2,
		},
		[33] = {
			pos = Vector(2.75, 4, -18.65),
			ang =  Angle(270, 0, 337.5),
			scl = Vector(1.2, 0, 1.5),
			mat = "fsign2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[34] = {
			pos = Vector(-3, 2, -19),
			ang =  Angle(0, 0, 0),
			scl = Vector(0.2, 2, 0.2),
			mat = "metal1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 0.2,
			uvScaleY = 2,
		},
		[35] = {
			pos = Vector(-2.75, 4, -18.7),
			ang =  Angle(270, 0, 22.5),
			scl = Vector(1.2, 1, 1.5),
			mat = "fsign3",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[36] = {
			pos = Vector(5, 2, -40),
			ang =  Angle(0, 0, 0),
			scl = Vector(0.2, 2, 0.2),
			mat = "metal1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 0.2,
			uvScaleY = 2,
		},
		[37] = {
			pos = Vector(5, 4, -39.75),
			ang =  Angle(270, 0, 0),
			scl = Vector(1.2, 1, 1.2),
			mat = "fsign4",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = -1,
			uvScaleY = -1,
		},
		[38] = {
			pos = Vector(-5, 2, -40),
			ang =  Angle(0, 0, 0),
			scl = Vector(0.2, 2, 0.2),
			mat = "metal1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 0.2,
			uvScaleY = 2,
		},
		[39] = {
			pos = Vector(-5, 4, -39.75),
			ang =  Angle(270, 0, 0),
			scl = Vector(1.2, 1, 1.2),
			mat = "fsign4",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
	},
	lights = {
		[1] = {
			pos = Vector(0, -11, -41),
			int = 11,
			col = Vector(64, 255, 64),
		},
		[2] = {
			pos = Vector(8, 12, -47),
			int = 8,
			col = Vector(64, 255, 64),
		},
		[3] = {
			pos = Vector(-11, 6, -14),
			int = 7,
			col = Vector(255, 96, 96),
		},
		[4] = {
			pos = Vector(12, 6, -14),
			int = 7,
			col = Vector(255, 96, 96),
		},
		[5] = {
			pos = Vector(0, 5, 5),
			int = 4,
			col = Vector(255, 16, 16),
		},
	},
	tiles = {
		[0] = {[0] = 1, [1] = 4, [2] = 2, [-2] = 1, [-5] = 1, [-12] = 6, [-11] = 1, [-4] = 1, [-10] = 5, [-9] = 1, [-8] = 1, [-3] = 1, [-7] = 1, [-1] = 1, [-6] = 1, },
		[1] = {[0] = 2, [1] = 2, [-2] = 1, [-5] = 6, [-12] = 6, [-11] = 1, [-4] = 1, [-10] = 1, [-9] = 1, [-8] = 6, [-3] = 1, [-7] = 6, [-1] = 2, [-6] = 6, },
		[2] = {[-2] = 1, [-5] = 6, [-12] = 6, [-11] = 6, [-4] = 1, [-10] = 6, [-9] = 6, [-8] = 6, [-3] = 1, [-7] = 6, [-1] = 2, [-6] = 6, },
		[-2] = {[-2] = 1, [-5] = 6, [-12] = 6, [-11] = 6, [-4] = 1, [-10] = 6, [-9] = 6, [-8] = 6, [-3] = 1, [-7] = 6, [-1] = 2, [-6] = 6, },
		[-5] = {[-2] = 2, [-5] = 2, [-3] = 2, [-1] = 2, [-4] = 2, },
		[4] = {[-2] = 1, [-5] = 6, [-12] = 6, [-11] = 6, [-4] = 1, [-10] = 6, [-9] = 6, [-8] = 6, [-3] = 1, [-7] = 6, [-1] = 2, [-6] = 6, },
		[3] = {[-2] = 1, [-5] = 6, [-12] = 6, [-11] = 6, [-4] = 1, [-10] = 6, [-9] = 6, [-8] = 6, [-3] = 1, [-7] = 6, [-1] = 2, [-6] = 6, },
		[-3] = {[-2] = 1, [-5] = 6, [-12] = 6, [-11] = 6, [-4] = 1, [-10] = 6, [-9] = 6, [-8] = 6, [-3] = 2, [-7] = 6, [-1] = 2, [-6] = 6, },
		[-1] = {[0] = 2, [1] = 2, [-2] = 1, [-5] = 6, [-12] = 6, [-11] = 1, [-4] = 1, [-10] = 1, [-9] = 1, [-8] = 6, [-3] = 1, [-7] = 6, [-1] = 2, [-6] = 6, },
		[-4] = {[-2] = 1, [-5] = 6, [-12] = 6, [-11] = 6, [-4] = 1, [-10] = 6, [-9] = 6, [-8] = 6, [-3] = 1, [-7] = 6, [-1] = 2, [-6] = 6, },
		[5] = {[-2] = 2, [-5] = 2, [-3] = 2, [-4] = 2, [-1] = 2, },
	},
}

LoveJam.DeclareLevel("levelfinal", levelData)