LoveJam = LoveJam or {}
LvLK3D = LvLK3D or {}
local levelData = {
	name = "shadow2",
	gW = 0,
	gH = 0,
	deco = {
		[1] = {
			pos = Vector(6, 1, 0),
			ang =  Angle(0, 24, 0),
			scl = Vector(1, 1, 1),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
		},
		[2] = {
			pos = Vector(5, 1, -4),
			ang =  Angle(0, 45, 0),
			scl = Vector(1, 1, 1),
			mat = "none",
			mdl = "push_box",
			fullbright = false,
			shadow = true,
			shaded = true,
		},
		[3] = {
			pos = Vector(14, 2.85, 0),
			ang =  Angle(0, -90, 0),
			scl = Vector(1, 1, 1),
			mat = "robot_hull",
			mdl = "robot_hull",
			fullbright = false,
			shadow = true,
			shaded = true,
		},
		[4] = {
			pos = Vector(14, 2.85, 0),
			ang =  Angle(0, -90, 0),
			scl = Vector(1, 1, 1),
			mat = "robot_legl",
			mdl = "robot_legl",
			fullbright = false,
			shadow = true,
			shaded = true,
		},
		[5] = {
			pos = Vector(14, 2.85, 0),
			ang =  Angle(0, -90, 0),
			scl = Vector(1, 1, 1),
			mat = "robot_legr",
			mdl = "robot_legr",
			fullbright = false,
			shadow = true,
			shaded = true,
		},
		[6] = {
			pos = Vector(-16, 1, 0),
			ang =  Angle(0, 45, 0),
			scl = Vector(5, 0.25, 4),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
		},
	},
	lights = {
		[1] = {
			pos = Vector(0, 6, 6),
			int = 4,
			col = Vector(255, 0, 0),
		},
		[2] = {
			pos = Vector(0, 6, 0),
			int = 4,
			col = Vector(0, 255, 0),
		},
		[3] = {
			pos = Vector(0, 6, -6),
			int = 4,
			col = Vector(0, 0, 255),
		},
	},
}
LoveJam.DeclareLevel("shadow2", levelData)