LoveJam = LoveJam or {}
LvLK3D = LvLK3D or {}
local levelData = {
	name = "level1test",
	gW = 0,
	gH = 0,
	gOX = 0,
	gOY = 0,
	deco = {
		[1] = {
			pos = Vector(0, 0, -4),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 6),
			mat = "metal3",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[2] = {
			pos = Vector(24, 0, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 6),
			mat = "metal1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[3] = {
			pos = Vector(32, 6, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[4] = {
			pos = Vector(20, 6, -8),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 6, 2),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 4,
		},
		[5] = {
			pos = Vector(12, 0, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 6),
			mat = "metal2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[6] = {
			pos = Vector(12, 6, -24),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 6, 2),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 4,
		},
		[7] = {
			pos = Vector(-8, 6, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[8] = {
			pos = Vector(0, 6, 16),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 6, 2),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[9] = {
			pos = Vector(0, 0, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 6),
			mat = "metal1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[10] = {
			pos = Vector(-8, 6, 2),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 12),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 4,
		},
		[11] = {
			pos = Vector(0, 0, 8),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 6),
			mat = "metal3",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 4,
		},
		[12] = {
			pos = Vector(8, 6, 2),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 12),
			mat = "none",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 4,
		},
	},
	lights = {
		[1] = {
			pos = Vector(24, 10, -16),
			int = 6,
			col = Vector(255, 196, 128),
		},
		[2] = {
			pos = Vector(0, 10, 4),
			int = 6,
			col = Vector(255, 196, 128),
		},
	},
	tiles = {
		[0] = {[0] = 1, [1] = 1, [2] = 4, [3] = 1, [4] = 2, [-2] = 1, [-5] = 1, [-3] = 1, [-4] = 1, [-1] = 1, [-6] = 2, },
		[1] = {[0] = 1, [1] = 1, [2] = 1, [3] = 1, [4] = 2, [-2] = 1, [-5] = 1, [-3] = 1, [-4] = 1, [-1] = 1, [-6] = 2, },
		[2] = {[0] = 2, [1] = 2, [2] = 2, [3] = 2, [4] = 2, [-2] = 2, [-5] = 1, [-3] = 1, [-4] = 1, [-1] = 2, [-6] = 2, },
		[-2] = {[0] = 2, [1] = 2, [2] = 2, [3] = 2, [4] = 2, [-2] = 2, [-5] = 2, [-3] = 2, [-4] = 2, [-1] = 2, [-6] = 2, },
		[5] = {[-2] = 2, [-5] = 1, [-3] = 1, [-4] = 1, [-6] = 2, },
		[4] = {[-2] = 2, [-5] = 1, [-3] = 1, [-4] = 1, [-6] = 2, },
		[8] = {[-2] = 2, [-5] = 2, [-3] = 2, [-4] = 2, [-6] = 2, },
		[3] = {[-2] = 2, [-5] = 1, [-3] = 1, [-4] = 1, [-6] = 2, },
		[7] = {[-2] = 2, [-5] = 1, [-3] = 1, [-4] = 1, [-6] = 2, },
		[-1] = {[0] = 1, [1] = 1, [2] = 1, [3] = 1, [4] = 2, [-2] = 1, [-5] = 1, [-3] = 1, [-1] = 1, [-4] = 1, [-6] = 2, },
		[6] = {[-2] = 2, [-5] = 1, [-3] = 1, [-4] = 5, [-6] = 2, },
	},
}

LoveJam.DeclareLevel("level1test", levelData)