LoveJam = LoveJam or {}
LvLK3D = LvLK3D or {}
local levelData = {
	name = "level4",
	nextLevel = "level5",
	isNoVis = true,
	gW = 0,
	gH = 0,
	gOX = 0,
	gOY = 0,
	deco = {
		[1] = {
			pos = Vector(-4, 6, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[2] = {
			pos = Vector(0, 0, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[3] = {
			pos = Vector(4, 6, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[4] = {
			pos = Vector(0, 9, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 6),
			mat = "metal_wall_stack2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[5] = {
			pos = Vector(-6, 0, -6),
			ang =  Angle(0, 0, 0),
			scl = Vector(12, 1, 4),
			mat = "grate1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 4,
		},
		[6] = {
			pos = Vector(-14, -1, 8),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 1, 10),
			mat = "grate1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 10,
		},
		[7] = {
			pos = Vector(8, 6, -6),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 4),
			mat = "tile1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 6,
		},
		[8] = {
			pos = Vector(-6, 6, -12),
			ang =  Angle(0, 0, 0),
			scl = Vector(12, 6, 2),
			mat = "tile1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 6,
		},
		[9] = {
			pos = Vector(-20, 6, 22),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 32),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 32,
			uvScaleY = 6,
		},
		[10] = {
			pos = Vector(-8, 6, 22),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 20),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 20,
			uvScaleY = 6,
		},
		[11] = {
			pos = Vector(-8, 6, 0),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[12] = {
			pos = Vector(-8, 6, 44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[13] = {
			pos = Vector(-4, 6, 44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[14] = {
			pos = Vector(0, 6, 44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[15] = {
			pos = Vector(0, 6, 30),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 12),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 6,
		},
		[16] = {
			pos = Vector(12, 6, 16),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 6, 2),
			mat = "tile1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 6,
		},
		[17] = {
			pos = Vector(0, 6, 56),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 6, 2),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 6,
		},
		[18] = {
			pos = Vector(20, 6, 42),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 12),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 6,
		},
		[19] = {
			pos = Vector(20, 6, 28),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[20] = {
			pos = Vector(30, 6, 28),
			ang =  Angle(0, 0, 0),
			scl = Vector(8, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 6,
		},
		[21] = {
			pos = Vector(30, 6, 12),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 6,
		},
		[22] = {
			pos = Vector(40, 6, 16),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 6, 2),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[23] = {
			pos = Vector(40, 6, 24),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 6, 2),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[24] = {
			pos = Vector(40, 9, 20),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 3, 2),
			mat = "metal_wall_stack2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[25] = {
			pos = Vector(24, 6, 16),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[26] = {
			pos = Vector(40, 0, 20),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 2),
			mat = "grate1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 2,
		},
		[27] = {
			pos = Vector(30, -1, 20),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 1, 6),
			mat = "tile1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 6,
		},
		[28] = {
			pos = Vector(-8, -8, 30),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 12),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 8,
		},
		[29] = {
			pos = Vector(-14, -9, 16),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 7, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 7,
		},
		[30] = {
			pos = Vector(-20, -8, 36),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 18),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 8,
		},
		[31] = {
			pos = Vector(0, -8, 56),
			ang =  Angle(0, 0, 0),
			scl = Vector(18, 8, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 18,
			uvScaleY = 8,
		},
		[32] = {
			pos = Vector(0, -8, 44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[33] = {
			pos = Vector(-4, -8, 44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[34] = {
			pos = Vector(-8, -8, 44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[35] = {
			pos = Vector(0, -8, 30),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 12),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 8,
		},
		[36] = {
			pos = Vector(-16, -1, 24),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[37] = {
			pos = Vector(-12, -1, 34),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 8),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[38] = {
			pos = Vector(-16, -1, 44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[39] = {
			pos = Vector(-12, -1, 50),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 4),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 4,
		},
		[40] = {
			pos = Vector(0, -1, 52),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 1, 2),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 2,
		},
		[41] = {
			pos = Vector(8, -1, 42),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 8),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[42] = {
			pos = Vector(4, -1, 32),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[43] = {
			pos = Vector(10, -1, 28),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 1, 2),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 2,
		},
		[44] = {
			pos = Vector(12, -1, 22),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 4),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 4,
		},
		[45] = {
			pos = Vector(20, -1, 20),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 2),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 2,
		},
		[46] = {
			pos = Vector(14, -8, 16),
			ang =  Angle(0, 0, 0),
			scl = Vector(12, 8, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 8,
		},
		[47] = {
			pos = Vector(20, -8, 42),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 12),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 12,
			uvScaleY = 8,
		},
		[48] = {
			pos = Vector(20, -8, 28),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[49] = {
			pos = Vector(24, -8, 28),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 2),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[50] = {
			pos = Vector(28, -9, 22),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 7, 4),
			mat = "metal_wall2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 7,
		},
		[51] = {
			pos = Vector(4, -16, 36),
			ang =  Angle(0, 0, 0),
			scl = Vector(22, 1, 18),
			mat = "toxic",
			mdl = "plane",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 22,
			uvScaleY = 18,
		},
		[52] = {
			pos = Vector(0, 3, 7),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 0.5),
			mat = "metal3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[53] = {
			pos = Vector(43, 3, 20),
			ang =  Angle(0, 0, 0),
			scl = Vector(0.5, 3, 2),
			mat = "metal3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[54] = {
			pos = Vector(12, 12, 22),
			ang =  Angle(180, 0, 0),
			scl = Vector(36, 1, 36),
			mat = "metal4",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 36,
			uvScaleY = 36,
		},
		[55] = {
			pos = Vector(-16, 2.5, -8),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 2, 2),
			mat = "silo_sheet",
			mdl = "silo",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[56] = {
			pos = Vector(0, 3, -9.75),
			ang =  Angle(270, 0, 0),
			scl = Vector(1, 1, 1),
			mat = "sign2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[57] = {
			pos = Vector(-17.75, 3, -1),
			ang =  Angle(270, 0, 90),
			scl = Vector(1, 1, 1),
			mat = "sign3",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[58] = {
			pos = Vector(-16, 1, 11),
			ang =  Angle(0, 337.5, 0),
			scl = Vector(1.5, 1, 1.5),
			mat = "metal2",
			mdl = "push_box",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[59] = {
			pos = Vector(-11, 1.4, 5),
			ang =  Angle(0, 45, 0),
			scl = Vector(2, 2, 2),
			mat = "barrel_sheet",
			mdl = "barrel",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[60] = {
			pos = Vector(-12, 0, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 0.1, 2),
			mat = "toxic",
			mdl = "cube",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 2,
			uvScaleY = 2,
		},
		[61] = {
			pos = Vector(-13, 1.5, 5),
			ang =  Angle(0, 292.5, 0),
			scl = Vector(2, 2, 2),
			mat = "barrel_sheet",
			mdl = "barrel",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[62] = {
			pos = Vector(-12, 3, 53.75),
			ang =  Angle(90, 180, 0),
			scl = Vector(1, 1, 1),
			mat = "sign2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[63] = {
			pos = Vector(33.75, 3, 17),
			ang =  Angle(90, 180, 270),
			scl = Vector(1, 1, 1),
			mat = "sign4",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
	},
	lights = {
		[1] = {
			pos = Vector(0, 5, 5),
			int = 4,
			col = Vector(255, 16, 16),
		},
		[2] = {
			pos = Vector(0, 10, -6),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[3] = {
			pos = Vector(-14, 10, 6),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[4] = {
			pos = Vector(-14, -16, 32),
			int = 16,
			col = Vector(64, 255, 64),
		},
		[5] = {
			pos = Vector(8, 10, 32),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[6] = {
			pos = Vector(22, -16, 22),
			int = 16,
			col = Vector(64, 255, 64),
		},
		[7] = {
			pos = Vector(8, -16, 50),
			int = 16,
			col = Vector(64, 255, 64),
		},
		[8] = {
			pos = Vector(-14, 10, 49),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[9] = {
			pos = Vector(30, 10, 20),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[10] = {
			pos = Vector(41, 5, 20),
			int = 4,
			col = Vector(255, 16, 16),
		},
		[11] = {
			pos = Vector(-12, 1, 3),
			int = 2,
			col = Vector(64, 255, 64),
		},
	},
	tiles = {
		[0] = {[0] = 1, [1] = 4, [2] = 2, [5] = 2, [6] = 2, [7] = 2, [8] = 2, [9] = 2, [10] = 2, [11] = 2, [12] = 6, [13] = 1, [14] = 2, [-2] = 1, [-1] = 1, [-3] = 2, },
		[1] = {[0] = 2, [1] = 2, [2] = 2, [4] = 2, [5] = 3, [6] = 3, [7] = 1, [8] = 1, [9] = 1, [10] = 6, [11] = 6, [12] = 6, [13] = 1, [14] = 2, [-2] = 1, [-1] = 1, [-3] = 2, },
		[2] = {[4] = 2, [5] = 3, [6] = 6, [7] = 1, [8] = 6, [9] = 1, [10] = 1, [11] = 1, [12] = 1, [13] = 1, [14] = 2, [-1] = 2, [-2] = 2, },
		[3] = {[4] = 2, [5] = 1, [6] = 1, [7] = 1, [8] = 3, [9] = 3, [10] = 3, [11] = 3, [12] = 3, [13] = 6, [14] = 2, },
		[4] = {[4] = 2, [5] = 1, [6] = 6, [7] = 3, [8] = 3, [9] = 3, [10] = 3, [11] = 3, [12] = 6, [13] = 6, [14] = 2, },
		[5] = {[4] = 2, [5] = 1, [6] = 6, [7] = 2, [8] = 2, [9] = 2, [10] = 2, [11] = 2, [12] = 2, [13] = 2, },
		[6] = {[3] = 2, [4] = 2, [5] = 1, [6] = 6, [7] = 2, },
		[7] = {[3] = 2, [4] = 1, [5] = 1, [6] = 1, [7] = 2, },
		[8] = {[3] = 2, [4] = 1, [5] = 1, [6] = 1, [7] = 2, },
		[-1] = {[0] = 2, [1] = 2, [2] = 2, [11] = 2, [12] = 6, [13] = 1, [14] = 2, [-2] = 1, [-1] = 1, [-3] = 2, },
		[-2] = {[0] = 2, [1] = 2, [2] = 2, [3] = 2, [4] = 2, [5] = 2, [6] = 2, [7] = 2, [8] = 2, [9] = 2, [10] = 2, [11] = 2, [12] = 6, [13] = 1, [14] = 2, [-1] = 1, [-2] = 1, [-3] = 2, },
		[-5] = {[0] = 2, [1] = 2, [2] = 2, [3] = 2, [4] = 2, [5] = 2, [6] = 2, [7] = 2, [8] = 2, [9] = 2, [10] = 2, [11] = 2, [12] = 2, [13] = 2, [-1] = 2, [-2] = 2, },
		[-3] = {[0] = 1, [1] = 2, [2] = 1, [3] = 1, [4] = 1, [5] = 6, [6] = 6, [7] = 1, [8] = 1, [9] = 1, [10] = 1, [11] = 6, [12] = 1, [13] = 1, [14] = 2, [-2] = 1, [-1] = 1, [-3] = 2, },
		[11] = {[4] = 2, [5] = 1, [6] = 2, },
		[-4] = {[0] = 1, [1] = 1, [2] = 1, [3] = 2, [4] = 1, [5] = 1, [6] = 1, [7] = 1, [8] = 6, [9] = 6, [10] = 1, [11] = 1, [12] = 1, [13] = 6, [14] = 2, [-1] = 1, [-2] = 2, [-3] = 2, },
		[10] = {[4] = 2, [5] = 5, [6] = 2, },
		[9] = {[3] = 2, [4] = 2, [5] = 1, [6] = 2, [7] = 2, },
	},
}

LoveJam.DeclareLevel("level4", levelData)