LoveJam = LoveJam or {}
LvLK3D = LvLK3D or {}
local levelData = {
	name = "level5",
	nextLevel = "level6",
	isNoVis = true,
	gW = 0,
	gH = 0,
	gOX = 0,
	gOY = 0,
	deco = {
		[1] = {
			pos = Vector(0, 0, -6),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 1, 4),
			mat = "tile2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 4,
		},
		[2] = {
			pos = Vector(0, 0, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[3] = {
			pos = Vector(-4, 6, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[4] = {
			pos = Vector(4, 6, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[5] = {
			pos = Vector(0, 9, 4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 6),
			mat = "metal_wall_stack2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[6] = {
			pos = Vector(0, 3, 8),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 0.5),
			mat = "metal3",
			mdl = "cube",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[7] = {
			pos = Vector(0, 0, -18),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 8),
			mat = "tile2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 8,
		},
		[8] = {
			pos = Vector(-8, 0, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 10),
			mat = "tile2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 10,
		},
		[9] = {
			pos = Vector(8, 0, -16),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 10),
			mat = "tile2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 10,
		},
		[10] = {
			pos = Vector(0, -1, -30),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 1, 4),
			mat = "tile2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 4,
		},
		[11] = {
			pos = Vector(0, -9, -32),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 7, 2),
			mat = "concrete2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 7,
		},
		[12] = {
			pos = Vector(-4, 6, -18),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 8),
			mat = "metal_wall1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 6,
		},
		[13] = {
			pos = Vector(4, 6, -18),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 8),
			mat = "metal_wall1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 8,
			uvScaleY = 6,
		},
		[14] = {
			pos = Vector(-8, 6, -4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[15] = {
			pos = Vector(8, 6, -4),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[16] = {
			pos = Vector(-12, 6, -42),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 36),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 36,
			uvScaleY = 6,
		},
		[17] = {
			pos = Vector(12, 6, -42),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 36),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 36,
			uvScaleY = 6,
		},
		[18] = {
			pos = Vector(0, -1, -44),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 1, 2),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 2,
		},
		[19] = {
			pos = Vector(8, -1, -38),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 4),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 4,
		},
		[20] = {
			pos = Vector(0, -1, -58),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 1, 4),
			mat = "tile1",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 4,
		},
		[21] = {
			pos = Vector(-8, -1, -50),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 4),
			mat = "grate2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 4,
		},
		[22] = {
			pos = Vector(0, 0, -70),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 1, 8),
			mat = "tile1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 8,
		},
		[23] = {
			pos = Vector(12, -8, -44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 10),
			mat = "concrete2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 8,
		},
		[24] = {
			pos = Vector(-12, -8, -44),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 8, 10),
			mat = "concrete2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 8,
		},
		[25] = {
			pos = Vector(0, -9, -56),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 7, 2),
			mat = "concrete2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 10,
			uvScaleY = 7,
		},
		[26] = {
			pos = Vector(0, -16, -44),
			ang =  Angle(0, 0, 0),
			scl = Vector(10, 1, 10),
			mat = "toxic",
			mdl = "plane",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 10,
			uvScaleY = 10,
		},
		[27] = {
			pos = Vector(-4, 6, -60),
			ang =  Angle(0, 0, 0),
			scl = Vector(6, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 6,
			uvScaleY = 6,
		},
		[28] = {
			pos = Vector(8, 6, -60),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[29] = {
			pos = Vector(-6, 6, -80),
			ang =  Angle(0, 0, 0),
			scl = Vector(4, 6, 2),
			mat = "metal_wall3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 4,
			uvScaleY = 6,
		},
		[30] = {
			pos = Vector(0, 6, -84),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[31] = {
			pos = Vector(8, 6, -84),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 6, 6),
			mat = "metal_wall_stack3",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[32] = {
			pos = Vector(4, 9, -84),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 6),
			mat = "metal_wall_stack2",
			mdl = "cube",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[33] = {
			pos = Vector(4, 0, -84),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 1, 6),
			mat = "grate1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 6,
		},
		[34] = {
			pos = Vector(-4, 2, -72),
			ang =  Angle(0, 337.5, 0),
			scl = Vector(1.5, 2, 1.5),
			mat = "metal2",
			mdl = "push_box",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[35] = {
			pos = Vector(4, 2.5, -68),
			ang =  Angle(0, 337.5, 0),
			scl = Vector(2, 2, 2),
			mat = "silo_sheet",
			mdl = "silo",
			fullbright = false,
			shadow = true,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = 1,
		},
		[36] = {
			pos = Vector(4, 3, -88),
			ang =  Angle(0, 0, 0),
			scl = Vector(2, 3, 1),
			mat = "metal3",
			mdl = "cube",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 2,
			uvScaleY = 3,
		},
		[37] = {
			pos = Vector(0, 12, -40),
			ang =  Angle(180, 0, 0),
			scl = Vector(14, 1, 38),
			mat = "metal4",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 14,
			uvScaleY = 38,
		},
		[38] = {
			pos = Vector(4, 14, -51),
			ang =  Angle(315, 45, 0),
			scl = Vector(3, 3, 3),
			mat = "toxic",
			mdl = "cube",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 3,
			uvScaleY = 3,
		},
		[39] = {
			pos = Vector(4, -2, -51),
			ang =  Angle(0, 45, 0),
			scl = Vector(1, 14, 1),
			mat = "toxic",
			mdl = "cube",
			fullbright = true,
			shadow = false,
			shaded = false,
			uvScaleX = 1,
			uvScaleY = 14,
		},
		[40] = {
			pos = Vector(-4, 3, -9.75),
			ang =  Angle(270, 0, 0),
			scl = Vector(1, 1, 1),
			mat = "sign1",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[41] = {
			pos = Vector(4, 3, -9.75),
			ang =  Angle(270, 0, 0),
			scl = Vector(1, 1, 1),
			mat = "sign3",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[42] = {
			pos = Vector(0, 3, -57.75),
			ang =  Angle(270, 0, 0),
			scl = Vector(1, 1, 1),
			mat = "sign4",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
		[43] = {
			pos = Vector(0, 3, -77.75),
			ang =  Angle(270, 0, 0),
			scl = Vector(1, 1, 1),
			mat = "sign2",
			mdl = "plane",
			fullbright = false,
			shadow = false,
			shaded = true,
			uvScaleX = 1,
			uvScaleY = -1,
		},
	},
	lights = {
		[1] = {
			pos = Vector(0, 5, 6),
			int = 4,
			col = Vector(255, 16, 16),
		},
		[2] = {
			pos = Vector(0, 10, -18),
			int = 4,
			col = Vector(128, 255, 128),
		},
		[3] = {
			pos = Vector(8, 10, -18),
			int = 4,
			col = Vector(128, 128, 255),
		},
		[4] = {
			pos = Vector(-8, 10, -18),
			int = 4,
			col = Vector(255, 128, 128),
		},
		[5] = {
			pos = Vector(0, 9, -7),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[6] = {
			pos = Vector(0, -15, -44),
			int = 16,
			col = Vector(16, 255, 16),
		},
		[7] = {
			pos = Vector(-2, 11, -70),
			int = 4,
			col = Vector(255, 196, 128),
		},
		[8] = {
			pos = Vector(4, 5, -86),
			int = 4,
			col = Vector(255, 16, 16),
		},
		[9] = {
			pos = Vector(4, 10, -51),
			int = 8,
			col = Vector(64, 255, 64),
		},
	},
	tiles = {
		[0] = {[0] = 1, [1] = 4, [2] = 2, [-14] = 1, [-2] = 1, [-12] = 6, [-11] = 1, [-10] = 6, [-9] = 6, [-8] = 1, [-19] = 1, [-7] = 1, [-1] = 1, [-6] = 1, [-5] = 1, [-4] = 1, [-21] = 2, [-22] = 2, [-17] = 1, [-20] = 2, [-3] = 1, [-18] = 1, [-16] = 1, [-15] = 2, [-13] = 6, },
		[1] = {[0] = 2, [1] = 2, [2] = 2, [-14] = 1, [-2] = 1, [-12] = 6, [-11] = 1, [-10] = 6, [-9] = 6, [-8] = 1, [-19] = 1, [-7] = 1, [-1] = 1, [-6] = 2, [-5] = 2, [-4] = 2, [-21] = 5, [-22] = 1, [-18] = 1, [-20] = 1, [-3] = 2, [-17] = 2, [-16] = 1, [-15] = 1, [-13] = 6, },
		[2] = {[-14] = 1, [-2] = 1, [-12] = 6, [-11] = 1, [-10] = 1, [-9] = 1, [-8] = 1, [-19] = 1, [-7] = 1, [-1] = 2, [-6] = 1, [-5] = 1, [-4] = 1, [-21] = 2, [-22] = 2, [-18] = 1, [-20] = 2, [-3] = 1, [-17] = 1, [-16] = 1, [-15] = 2, [-13] = 6, },
		[3] = {[-14] = 2, [-2] = 2, [-12] = 2, [-11] = 2, [-10] = 2, [-9] = 2, [-8] = 2, [-19] = 2, [-17] = 2, [-6] = 2, [-5] = 2, [-4] = 2, [-18] = 2, [-20] = 2, [-3] = 2, [-7] = 2, [-16] = 2, [-15] = 2, [-13] = 2, },
		[-1] = {[0] = 2, [1] = 2, [2] = 2, [-14] = 1, [-2] = 1, [-12] = 6, [-11] = 1, [-10] = 6, [-9] = 6, [-8] = 1, [-19] = 1, [-7] = 1, [-1] = 1, [-6] = 2, [-5] = 2, [-4] = 2, [-18] = 2, [-20] = 2, [-3] = 2, [-17] = 1, [-16] = 1, [-15] = 2, [-13] = 6, },
		[-2] = {[-14] = 1, [-2] = 1, [-12] = 1, [-11] = 1, [-10] = 6, [-9] = 6, [-8] = 1, [-19] = 1, [-7] = 1, [-1] = 2, [-6] = 1, [-5] = 1, [-4] = 1, [-18] = 1, [-20] = 2, [-3] = 1, [-17] = 1, [-16] = 1, [-15] = 2, [-13] = 1, },
		[-3] = {[-14] = 2, [-2] = 2, [-12] = 2, [-11] = 2, [-10] = 2, [-9] = 2, [-8] = 2, [-19] = 2, [-17] = 2, [-6] = 2, [-5] = 2, [-4] = 2, [-18] = 2, [-20] = 2, [-3] = 2, [-7] = 2, [-16] = 2, [-15] = 2, [-13] = 2, },
	},
}

LoveJam.DeclareLevel("level5", levelData)